### ISSUE TITLE
Битая ссылка

### ISSUE THREAD

**Issue by sinitcin** [rust-lang-ru/rustonomicon#14]
На странице https://github.com/ruRust/rustonomicon/blob/master/src/repr-rust.md есть битая ссылка 

>> типов динамического размера

Указывающая на https://github.com/ruRust/rustonomicon/blob/master/src/exotic-sizes.html#dynamically-sized-types-dsts

**Comment by ava57r** [comment]
Спасибо! Поправил https://github.com/rust-lang-ru/rustonomicon/commit/03f87a50177b80e6305268086653b44c701830ef
