### ISSUE TITLE
Битая ссылка 

### ISSUE THREAD

**Issue by sinitcin** [rust-lang-ru/rustonomicon#15]
#14 На странице https://github.com/ruRust/rustonomicon/blob/master/src/other-reprs.md
Есть текст 

> Если у типа есть drop flags, они все равно будут добавлены

Где drop flags указывает на 
> https://github.com/ruRust/rustonomicon/blob/master/src/drop-flags.html

**Comment by ava57r** [comment]
Спасибо! Поправил https://github.com/rust-lang-ru/rustonomicon/commit/91544256514e4a5354443ab97d1047047a22086d
