### ISSUE TITLE
Битая ссылка 

### ISSUE THREAD

**Issue by Nikita-prog-art** [rust-lang-ru/rustonomicon#20]
https://github.com/rust-lang-ru/rustonomicon/blob/master/src/meet-safe-and-unsafe.md
Битые ссылки на гонки данных

**Comment by Nikita-prog-art** [comment]
Вместо .md .html

**Comment by ava57r** [comment]
Спасибо!
поправил https://github.com/rust-lang-ru/rustonomicon/commit/699c0419c81025e25d0b5057a80e8961c4f18120
